# Site settings
title: Code Talk
header-img: img/home-bg.png
email: vanita112003@gmail.com
copyright_name: vanitanaidu
description: > # this means to ignore newlines until "baseurl:"
  My Adventures in Ruby and Javascript
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vanitanaidu
learn_profile: vanitanaidu
email_username: vanita112003@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
